### ISSUE TITLE
Many questions have incorrect answers/are too easy

### ISSUE THREAD

**Issue by Sinjo** [Sinjo/Trivial#2]
There are many questions which have multiple correct answers (eg artists with multiple hits listed, but only one accepted as correct).

Also the arithmetic questions are just terrible and are far too easy. Maybe people would rather have some differential equations (in seriousness, generate harder things)?

**Comment by Behzad9** [comment]
hi dear sinijo
sorry,what program used for make questions?
thanks

**Comment by Sinjo** [comment]
They were [extracted from DBpedia](https://github.com/Sinjo/Trivial/blob/adc4230794d594776415d8dac56a0f86cf55ee86/assets/questions/questions-best-actor#L1).

**Comment by Sinjo** [comment]
Closing all issues as this project is unmaintained.
